<?php

declare(strict_types=1);

use ARM\Migrations\MigrationInterface;
use PDO;

return new class implements MigrationInterface {
    public function getId(): string
    {
        return '20240701000000_create_core_tables';
    }

    public function up(PDO $pdo, string $prefix, string $charsetCollate): void
    {
        $tables = [
            'customers' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_customers` (
                id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                first_name VARCHAR(100) NOT NULL,
                last_name VARCHAR(100) NOT NULL,
                email VARCHAR(200) NOT NULL,
                phone VARCHAR(50) NULL,
                address VARCHAR(200) NULL,
                city VARCHAR(100) NULL,
                state VARCHAR(100) NULL,
                zip VARCHAR(20) NULL,
                notes TEXT NULL,
                tax_exempt TINYINT(1) NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL,
                updated_at DATETIME NULL
            ) %s;",
            'vehicles' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_vehicles` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                customer_id BIGINT UNSIGNED NOT NULL,
                user_id BIGINT UNSIGNED NULL,
                year SMALLINT NULL,
                make VARCHAR(80) NULL,
                model VARCHAR(120) NULL,
                engine VARCHAR(120) NULL,
                trim VARCHAR(120) NULL,
                vin VARCHAR(32) NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                deleted_at DATETIME NULL,
                PRIMARY KEY  (id),
                KEY cust (customer_id),
                KEY user (user_id),
                KEY yr (year)
            ) %s;",
            'service_types' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_service_types` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                name VARCHAR(128) NOT NULL,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                sort_order INT NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                PRIMARY KEY  (id),
                UNIQUE KEY name (name),
                KEY active (is_active),
                KEY sort (sort_order)
            ) %s;",
            'time_entries' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_time_entries` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                job_id BIGINT UNSIGNED NOT NULL,
                estimate_id BIGINT UNSIGNED NOT NULL,
                technician_id BIGINT UNSIGNED NOT NULL,
                source ENUM('technician','admin') NOT NULL DEFAULT 'technician',
                start_at DATETIME NOT NULL,
                end_at DATETIME NULL,
                duration_minutes INT UNSIGNED NULL,
                notes TEXT NULL,
                start_location LONGTEXT NULL,
                end_location LONGTEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                PRIMARY KEY  (id),
                KEY idx_job (job_id),
                KEY idx_estimate (estimate_id),
                KEY idx_technician (technician_id),
                KEY idx_open (technician_id, end_at)
            ) %s;",
            'time_adjustments' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_time_adjustments` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                time_entry_id BIGINT UNSIGNED NOT NULL,
                admin_id BIGINT UNSIGNED NOT NULL,
                action VARCHAR(32) NOT NULL DEFAULT 'update',
                previous_start DATETIME NULL,
                previous_end DATETIME NULL,
                previous_duration INT NULL,
                new_start DATETIME NULL,
                new_end DATETIME NULL,
                new_duration INT NULL,
                reason TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY  (id),
                KEY idx_entry (time_entry_id),
                KEY idx_admin (admin_id)
            ) %s;",
            'inventory' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_inventory` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                name VARCHAR(190) NOT NULL,
                sku VARCHAR(190) NULL,
                location VARCHAR(190) NULL,
                qty_on_hand INT NOT NULL DEFAULT 0,
                low_stock_threshold INT NOT NULL DEFAULT 0,
                reorder_quantity INT NOT NULL DEFAULT 0,
                cost DECIMAL(12,2) NOT NULL DEFAULT 0.00,
                price DECIMAL(12,2) NOT NULL DEFAULT 0.00,
                vendor VARCHAR(190) NULL,
                notes TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                PRIMARY KEY  (id),
                KEY sku (sku),
                KEY location (location),
                KEY vendor (vendor),
                KEY qty (qty_on_hand),
                KEY threshold (low_stock_threshold)
            ) %s;",
            'reminder_preferences' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_reminder_preferences` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                customer_id BIGINT UNSIGNED NULL,
                email VARCHAR(200) NULL,
                phone VARCHAR(50) NULL,
                timezone VARCHAR(64) NOT NULL DEFAULT 'UTC',
                preferred_channel ENUM('none','email','sms','both') NOT NULL DEFAULT 'email',
                lead_days SMALLINT UNSIGNED NOT NULL DEFAULT 3,
                preferred_hour TINYINT UNSIGNED NOT NULL DEFAULT 9,
                is_active TINYINT(1) NOT NULL DEFAULT 1,
                source VARCHAR(64) NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                PRIMARY KEY  (id),
                UNIQUE KEY uniq_customer (customer_id),
                UNIQUE KEY uniq_email (email),
                KEY idx_channel (preferred_channel),
                KEY idx_active (is_active)
            ) %s;",
            'reminder_campaigns' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_reminder_campaigns` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                name VARCHAR(190) NOT NULL,
                description TEXT NULL,
                status ENUM('draft','active','paused','archived') NOT NULL DEFAULT 'draft',
                channel ENUM('email','sms','both') NOT NULL DEFAULT 'email',
                frequency_unit ENUM('one_time','daily','weekly','monthly') NOT NULL DEFAULT 'one_time',
                frequency_interval SMALLINT UNSIGNED NOT NULL DEFAULT 1,
                next_run_at DATETIME NULL,
                last_run_at DATETIME NULL,
                email_subject VARCHAR(190) NULL,
                email_body LONGTEXT NULL,
                sms_body TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                PRIMARY KEY  (id),
                KEY idx_status (status),
                KEY idx_next (next_run_at)
            ) %s;",
            'reminder_logs' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_reminder_logs` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                campaign_id BIGINT UNSIGNED NOT NULL,
                preference_id BIGINT UNSIGNED NOT NULL,
                customer_id BIGINT UNSIGNED NULL,
                channel ENUM('email','sms') NOT NULL DEFAULT 'email',
                status ENUM('queued','pending','sent','failed','skipped') NOT NULL DEFAULT 'queued',
                scheduled_for DATETIME NOT NULL,
                sent_at DATETIME NULL,
                message_body LONGTEXT NULL,
                error_message TEXT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY  (id),
                KEY idx_campaign (campaign_id),
                KEY idx_pref (preference_id),
                KEY idx_status (status),
                KEY idx_scheduled (scheduled_for)
            ) %s;",
            'vehicle_data' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_vehicle_data` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                year SMALLINT NOT NULL,
                make VARCHAR(64) NOT NULL,
                model VARCHAR(64) NOT NULL,
                engine VARCHAR(128) NOT NULL,
                transmission VARCHAR(80) NOT NULL,
                drive VARCHAR(32) NOT NULL,
                trim VARCHAR(128) NOT NULL,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at DATETIME NULL,
                PRIMARY KEY  (id),
                UNIQUE KEY combo (year, make, model, engine, transmission, drive, trim),
                KEY yr (year),
                KEY mk (make),
                KEY mdl (model),
                KEY eng (engine),
                KEY trn (transmission),
                KEY drv (drive),
                KEY trm (trim)
            ) %s;",
            'estimate_requests' => "CREATE TABLE IF NOT EXISTS `{$prefix}arm_estimate_requests` (
                id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
                vehicle_year SMALLINT NULL,
                vehicle_make VARCHAR(64) NULL,
                vehicle_model VARCHAR(64) NULL,
                vehicle_engine VARCHAR(128) NULL,
                vehicle_transmission VARCHAR(80) NULL,
                vehicle_drive VARCHAR(32) NULL,
                vehicle_trim VARCHAR(128) NULL,
                vehicle_other TEXT NULL,
                service_type_id BIGINT UNSIGNED NULL,
                issue_description TEXT NULL,
                first_name VARCHAR(64) NOT NULL,
                last_name VARCHAR(64) NOT NULL,
                email VARCHAR(128) NOT NULL,
                phone VARCHAR(32) NULL,
                customer_address VARCHAR(200) NOT NULL,
                customer_city VARCHAR(100) NOT NULL,
                customer_zip VARCHAR(20) NOT NULL,
                service_same_as_customer TINYINT(1) NOT NULL DEFAULT 0,
                service_address VARCHAR(200) NOT NULL,
                service_city VARCHAR(100) NOT NULL,
                service_zip VARCHAR(20) NOT NULL,
                delivery_email TINYINT(1) NOT NULL DEFAULT 0,
                delivery_sms TINYINT(1) NOT NULL DEFAULT 0,
                delivery_both TINYINT(1) NOT NULL DEFAULT 0,
                terms_accepted TINYINT(1) NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                KEY stype (service_type_id),
                KEY created_at (created_at)
            ) %s;",
        ];

        foreach ($tables as $sql) {
            $pdo->exec(sprintf($sql, $charsetCollate));
        }
    }
};
